### ISSUE TITLE
First class support for Windows

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#3]
I suspect that a lot of agency developers might be forced to use Windows machines, so our npm commands should support Windows. I think the best way to do that is to use a tool like [gulp.js](https://gulpjs.com/) so that build tasks can be done in a cross-platform way.

**Comment by dacresni** [comment]
This issue seems to assume ruby for windows doesn't exist. Ruby for Windows is alright and I think we should keep a single language process instead of calling back and forth between ruby and node. the npm build step seems to be looking for bundler which would have required me to install ruby on windows anyway, right?

**Comment by dacresni** [comment]
I've been using jekyll on windows for the past couple months now. Thanks to GitBash the only thing  that doesn't work is npm

**Comment by eddietejeda** [comment]
This should already be done of v1.3.0. We'd welcome testing and feedback from Windows users.
